### ISSUE TITLE
Finding the determinant hangs and basically never completes for large matrix

### ISSUE THREAD

**Issue by klivin** [altera2015/linalg#2]
Trying to do a determinant on a matrix never completes due to using Leibniz formula or Laplace expansion.

These algorithms complete in O(n!) time. 

So a 13x13 matrix would not even complete

Gauss elimination is O(n^3) which is much better.

**Comment by altera2015** [comment]
Hey klivin, I'm happy to take PR's for the Gauss elimination method.
